name: Update README with Latest Blog Posts

on:
  schedule:
    - cron: '0 * * * *'  
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Fetch Latest Blog Posts
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          pip install yq

          curl -s https://sieep-coding.github.io/rss.xml | \
          xq -r '.rss.channel.item | 
            map({
              title: .title, 
              link: (.link // .guid | sub("\\s+"; ""; "g")), 
              date: (.pubDate | strptime("%a, %d %b %Y %H:%M:%S GMT") | mktime)
            }) | 
            sort_by(.date) | reverse[:5] | 
            map("| " + (.date | strftime("%a, %d %b %Y")) + " | **[" + .title + "](" + .link + ")** |") | 
            join("\n")' > latest-posts.md

          echo -e "# Blog\n\n<!-- BLOG-POST-LIST:START -->\n| Date | Title |\n| --- | --- |" > README.tmp
          cat latest-posts.md >> README.tmp
          echo -e "\n<!-- BLOG-POST-LIST:END -->" >> README.tmp
          mv README.tmp README.md




      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Updated latest blog posts" || exit 0
          git push
