name: Update README with Latest Blog Posts

on:
  schedule:
    - cron: '0 * * * *'  
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Fetch Latest Blog Posts
        run: |
          curl -s https://nickstambaugh.vercel.app/rss.xml | \
          grep -E "<title>|<link>|<pubDate>" | \
          sed -e 's/<title>//g' -e 's/<\/title>//g' \
              -e 's/<link>//g' -e 's/<\/link>//g' \
              -e 's/<pubDate>//g' -e 's/<\/pubDate>//g' | \
          paste - - - | \
          sort -k3,3r | \
          head -n 5 | \
          awk -F '\t' '{print "| " $3 " | **[" $1 "](" $2 ")** |"}' > latest-posts.md

          awk '/<!-- BLOG-POST-LIST:START -->/{print; print content; found=1; next} /<!-- BLOG-POST-LIST:END -->/{found=0} !found' content="$(cat latest-posts.md)" README.md > README.tmp && mv README.tmp README.md


      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Updated latest blog posts" || exit 0
          git push
