name: Update README with Latest Blog Posts

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual execution

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch Latest Blog Posts
        run: |
          curl -s https://nickstambaugh.vercel.app/rss.xml | \
          xq -r '.rss.channel.item[:5] | map("| " + .pubDate[:16] + " | **[" + .title + "](" + .link + ")** |") | join("\n")' > latest-posts.md
          echo -e "<!-- BLOG-POST-LIST:START -->\n$(cat latest-posts.md)\n<!-- BLOG-POST-LIST:END -->" > README.md

      - name: Commit and Push Changes
        uses: actions-js/push@v1.3.0
        with:
          message: "Updated latest blog posts"
          branch: main
